grace-shopper-team-it/grace-shopper

client/components/obviousChange.js
=> Obvious change

client/components/index.js, client/components/obviousChange.js, client/components/products/DeleteProduct.js, client/components/products/EditProduct.js, client/components/products/Product.js, client/components/products/SingleProduct.js, client/routes.js, client/store/index.js, client/store/product.js, client/store/user.js, package-lock.json
=> adding edit and delete buttons on single product page for admins

client/components/user-home.spec.js, package.json, test-setup.js
=> adding test config file in root directory

.eslintrc.json, .gitignore, client/components/products/AddProduct.js, client/components/products/DeleteProduct.js, client/components/products/EditProduct.js, client/components/products/ProductForm.js, client/components/products/ProductForm.spec.js, client/components/products/SingleProduct.js, client/store/product.js, package-lock.json, public/style.css, server/api/index.js, server/api/products.admin.js, server/api/products.js, server/api/products.spec.js
=> 16 admin delete categories

.eslintrc.json, .gitignore, client/components/products/AddProduct.js, client/components/products/DeleteProduct.js, client/components/products/EditProduct.js, client/components/products/ProductForm.js, client/components/products/ProductForm.spec.js, client/components/products/SingleProduct.js, client/store/product.js, package-lock.json, public/style.css, server/api/index.js, server/api/products.admin.js, server/api/products.js, server/api/products.spec.js
=> 13 admin product v2

client/store/cart.js.orig, script/seed.js, server/api/orders.admin.js, server/api/orders.admin.spec.js, server/db/models/index.js
Minor changes -- added authentication for routes
=> Order management view #17

client/components/navbar.js, client/components/products/AllProducts.js, client/components/products/Product.js, client/routes.js, client/store/cart.js, package-lock.json, package.json
Added view cart link to navbar, made Product.js stateful & added form so you can change quantity before adding item to cart. Form's not working yet but it's rendering
=> Other new cart branch

client/components/products/AddProduct.js, client/components/products/CategoryForm.js, client/components/products/ProductForm.js, client/components/products/SingleProduct.js, client/store/product.js, package.json, server/api/products.admin.js, server/api/products.js, server/api/products.spec.js
Adding existing categories to existing products
=> 14 admin create categories

client/components/auth-form.js, client/components/navbar.js, client/components/products/ProductForm.js, client/components/users/user-home.js, client/store/user.js, server/api/auth.middleware.js, server/api/index.js, server/api/products.admin.js, server/api/products.js, server/api/users.admin.js, server/api/users.js
some of these changes might be identical to my pull request (sorry still getting the hang of this pull request thing).
=> Update user thunk #65

client/components/products/ProductForm.js, client/store/user.js, server/api/auth.middleware.js, server/api/products.admin.js, server/api/products.js, server/api/users.admin.js, server/api/users.js
Added security routes for server side product and user admin routes. Non admin users will also be redirected if they try to access product forms on the front end.
=> Admin security #63

client/components/auth-form.js, client/components/index.js, client/components/users/SingleUser.js, client/components/users/UserInfo.js, client/components/users/UserList.js, client/routes.js, client/store/index.js, client/store/user.admin.js, server/api/auth.middleware.js, server/api/products.js, server/api/users.js, server/api/users.spec.js, server/auth/index.js, server/db/models/user.js
see commits for description. This also fixes a bug introduced in my last pull request involving product administration for admin users
=> Promote admin status #20

client/components/auth-form.css, client/components/auth-form.js, client/components/navbar.js, public/index.html
=> Adding some style

client/components/cart/Cart.js, client/components/cart/CartItem.js
=> Cart total $$ rendering & updating

client/components/products/CategoryForm.js, client/components/users/AdminActions.js, client/components/users/SingleUser.js, client/store/user.admin.js, server/api/users.admin.js, server/api/users.js
Admins can change isAdmin to true or false as the case may be.
=> change user status

client/components/orders/SingleOrderPage.js, client/components/users/SingleUser.js, server/api/users.js
adding order detail to users/:id page. Non-admins don't have access yet to the order api route
=> Account management #8

client/components/products/AddReview.js, client/components/products/Reviews.css, client/components/products/Reviews.js, client/components/products/SingleProduct.js, package-lock.json, server/api/products.js
=> 9 authenticated users reviews

client/components/products/SingleProduct.js, client/components/users/SingleUser.js, server/api/users.admin.js
fixed bug with updating user status
=> bugs fixed

client/components/products/Reviews.js, client/components/products/SingleProduct.js
=> reviews average working

client/components/products/EditProduct.js, client/components/products/ProductForm.js, client/components/products/SingleProduct.js, client/components/users/AdminActions.js, server/api/products.admin.js, server/api/products.js, server/db/models/product.js
admins can now add new categories to existing products when they are using the edit form. Also duplicate categories will not be added to the DB.
=> Adding categories bugs

server/db/models/user.js
Need to allow first and last name to be null so people can log in with Google
=> changed data validations for user

client/components/products/CategoryDropdown.js, client/components/products/Product.js, client/components/products/ProductsCard.js
=> price added to ProductCard and Products

client/components/orders/AllOrders.js, client/components/orders/SingleOrderItem.js, client/components/orders/SingleOrderPage.js, client/components/orders/StatusDropDown.js, client/store/order.js, server/api/orders.admin.js
=> Orders views bug fixes

server/db/seed.js
=> Clown seed

client/components/cart/Cart.js, client/components/cart/CartItem.js, client/components/products/Product.js
=> style added to cart

client/components/orders/SingleOrderPage.js, client/components/products/Product.js, client/components/users/SingleUser.js, client/components/users/user-home.js, package-lock.json, package.json
changed bug with the huge images 
made it so users can get a link to their orders and stuff
=> Bug fix images home

client/components/cart/CartItem.js, client/components/products/FormErrors.js, client/components/products/Product.js, server/db/models/productOrder.js
Inventory working, forms validate, some other stuff
=> Inventory working, quantity forms validate before updating, some other stuff

client/components/products/AddReview.js, client/components/products/AllProducts.js, client/components/products/CategoryDropdown.js, client/components/products/Product.js
=> image problem fixed

README.md, server/db/index.js
=> updating README

package-lock.json, package.json
=> remove engines section from package.json
